import {Game} from "@/components/GameCard";

export const PLACEHOLDER_GAMES: Game[] = [
  {
    title: 'Splatoon 2',
    platform: 'Nintendo Switch',
    genre: 'Shooter',
    status: 'playing',
    publisher: 'Nintendo of Europe',
    rating: 5,
    metacriticScore: 84,
    ageRating: 12,
    realaseDate: "21.07.2017",
    webPage: "http://splatoon.nintendo.com/",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    series: [{"id":558975,"name":"Splatoon 3","released":"2022-09-09","background_image":"https://media.rawg.io/media/games/360/360ac0a839ab0f0d9a70b35d38264cb0.jpg"},{"id":23935,"name":"Splatoon","released":"2015-05-29","background_image":"https://media.rawg.io/media/games/c2f/c2f94f3fefa98453f33f2b6abb6ae103.jpg"}],
    play_time: 10000,
    progress_value: 98,
    progress_total: 100,
    start_date: "2025-11-11",
    end_date: "2025-11-12",
    image_url: [
      "https://media.rawg.io/media/games/24b/24b68f500fd138c3146d8856f0dd55b4.jpg",
      "https://media.rawg.io/media/screenshots/3ea/3eadccae65f82027a0e0ddc1f4ea5d52.jpg",
      "https://media.rawg.io/media/screenshots/ea6/ea669a514a8fdd905b5d67384561014b.jpg",
      "https://media.rawg.io/media/screenshots/441/44158afb4810a7141760dc3b03d143ba.jpg"]
},
  {
    title: 'The Legend of Zelda: Tears of the Kingdom',
    platform: 'Nintendo Switch 2',
    genre: 'Adventure',
    status: 'playing',
    rating: 4,
    metacriticScore: 95,
    ageRating: 12,
    realaseDate: "21.07.2018",
    webPage: "http://zelda.nintendo.com/",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    play_time: 120,
    progress_value: 106,
    progress_total: 152,
    image_url: ['https://imgs.search.brave.com/2cSE4AyYrHjAAvueNp8XOOWOgsBWRCW-ZjnCKNcHXAI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwLnBvbHlnb25p/bWFnZXMuY29tL3dv/cmRwcmVzcy93cC1j/b250ZW50L3VwbG9h/ZHMvY2hvcnVzL3Vw/bG9hZHMvY2hvcnVz/X2Fzc2V0L2ZpbGUv/MjQ1ODI5MDQvemVs/ZGFfbWFzdGVyX3N3/b3JkX3RvdGsuanBn/P3E9NDkmZml0PWNy/b3Amdz02NDImaD0z/OTMmZHByPTI'
  ]},
      {
    title: 'Horizon Forbidden West',
    platform: 'PlayStation 5',
    genre: 'RPG',
    status: 'paused',
    rating: 4,
    metacriticScore: 90,
    ageRating: 16,
    realaseDate: "21.07.2023",
    webPage: "http://playstation.com",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    play_time: 98,
    progress_value: 78,
    progress_total: 112,
    image_url: ['https://media.rawg.io/media/games/bf7/bf73b105ccbba42107986bbcd96fcada.jpg']
  },
      {
    title: 'Kena: Bridge of Spirits',
    platform: 'PlayStation 5',
    genre: 'RPG',
    status: 'completed',
    rating: 5,
     metacriticScore: 98,
    ageRating: 12,
    realaseDate: "22.03.2022",
    webPage: "http://kenagame.com/",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    play_time: 114,
    progress_value: 100,
    progress_total: 100,
    image_url: ['https://media.rawg.io/media/games/91d/91ddeef8d5ebee7f21faa89efa0f2201.jpg']
  },
  {
    title: 'Persona 5 Royal',
    platform: 'PlayStation 5',
    status: 'dropped',
    rating: 1,
    metacriticScore: 22,
    ageRating: 12,
    realaseDate: "21.07.2017",
    webPage: "http://splatoon.nintendo.com/",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
    play_time: 102,
    progress_value: 0,
    progress_total: 100,
    image_url: ['https://imgs.search.brave.com/zJWaU601KmF-GXFWqrVQau3ilaFBFSmJ6T49xtUDBjo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvZmVhdHVy/ZWQvcGVyc29uYS01/LXBpY3R1cmVzLXZ4/eTNodTV5bzVjZWxo/bWIuanBn'
  ]},
  {
    title: 'Hollow Knight',
    platform: 'Nintendo Switch',
    status: 'backlog',
    rating: 3,
    metacriticScore: 84,
    ageRating: 12,
    realaseDate: "21.07.2017",
    webPage: "http://splatoon.nintendo.com/",
    about: 'For the first time, take Turf War battles on-the-go with the Nintendo Switch™ system, and use any of the console\'s portable play styles for intense local multiplayer* action. Even team up for new 4-player co-op fun in Salmon Run! Two years have passed since the original Splatoon™ game was released, and two years have also passed in Inkopolis! So expect a fresh wave of fashion, not to mention new weapons and gear. Dual wield the new Splat Dualies or stick to mainstays like chargers and rollers, which have been remixed with new strategic possibilities. As always, Turf War is the favored sport among Inklings, but they also dig ranked battles, taking down Octarians in a robust single-player campaign, and battling enemy Salmonids in one dangerous part-time job!',
    notes: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."',
   play_time: 102,
    image_url: ['https://imgs.search.brave.com/rGo8wNTrFG5myKCED8JEG-u_5X9FJ-L5JW9Pf_t5ENQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDcwOTc0/MDguanBn']
  },
]